package services_test

import (
	"fmt"
	"testing"

	"github.com/glebarez/sqlite"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"

	"storefront/apps/api/internal/models"
	"storefront/apps/api/internal/services"
)

// Generated by grit --tree. The hierarchy has invariants worth holding onto:
// a move carries its subtree, and a node can never end up inside itself.

func CategoryTreeTestDB(t *testing.T) *gorm.DB {
	t.Helper()
	db, err := gorm.Open(sqlite.Open(":memory:"), &gorm.Config{
		Logger: logger.Default.LogMode(logger.Silent),
	})
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	// SQLite does not enforce foreign keys unless asked, and Postgres always
	// does. Without this line these tests pass while the same code fails on the
	// first real project, which is exactly what happened: a root written with
	// parent_id = "" satisfied SQLite and violated the FK constraint on
	// Postgres.
	db.Exec("PRAGMA foreign_keys = ON")
	if err := db.AutoMigrate(&models.Category{}); err != nil {
		t.Fatalf("migrate: %v", err)
	}
	return db
}

// makeCategory creates a row, taking the parent as a plain string for readability
// at the call site. An empty string means a root, and reaches the database as
// NULL: the column is nullable because a foreign key constraint accepts NULL
// for "no parent" and rejects "".
func makeCategory(t *testing.T, db *gorm.DB, name, parentID string) models.Category {
	t.Helper()
	row := models.Category{Name: name}
	if parentID != "" {
		row.ParentID = &parentID
	}
	if err := db.Create(&row).Error; err != nil {
		t.Fatalf("create %s: %v", name, err)
	}
	return row
}

func TestCategoryTreePathsAndDepths(t *testing.T) {
	db := CategoryTreeTestDB(t)

	top := makeCategory(t, db, "Top", "")
	middle := makeCategory(t, db, "Middle", top.ID)
	bottom := makeCategory(t, db, "Bottom", middle.ID)

	if top.Path != "/"+top.ID+"/" || top.Depth != 0 {
		t.Errorf("root: path=%q depth=%d", top.Path, top.Depth)
	}
	if want := "/" + top.ID + "/" + middle.ID + "/"; middle.Path != want || middle.Depth != 1 {
		t.Errorf("child: path=%q depth=%d, want %q depth 1", middle.Path, middle.Depth, want)
	}
	if want := "/" + top.ID + "/" + middle.ID + "/" + bottom.ID + "/"; bottom.Path != want || bottom.Depth != 2 {
		t.Errorf("grandchild: path=%q depth=%d, want %q depth 2", bottom.Path, bottom.Depth, want)
	}

	// Read from the stored path, no query.
	if got := bottom.AncestorIDs(); len(got) != 2 || got[0] != top.ID || got[1] != middle.ID {
		t.Errorf("AncestorIDs = %v", got)
	}
	if !top.IsRoot() || bottom.IsRoot() {
		t.Error("IsRoot is wrong")
	}
}

func TestCategoryTreeRefusesAMissingParent(t *testing.T) {
	db := CategoryTreeTestDB(t)
	missing := "does-not-exist"
	row := models.Category{Name: "Orphan", ParentID: &missing}
	if err := db.Create(&row).Error; err == nil {
		t.Error("a child of a parent that does not exist must be refused")
	}
}

func TestCategoryTreeQueries(t *testing.T) {
	db := CategoryTreeTestDB(t)
	svc := services.NewCategoryTreeService(db)

	top := makeCategory(t, db, "Top", "")
	middle := makeCategory(t, db, "Middle", top.ID)
	bottom := makeCategory(t, db, "Bottom", middle.ID)
	makeCategory(t, db, "Other", "")

	roots, err := svc.Roots()
	if err != nil {
		t.Fatalf("Roots: %v", err)
	}
	if len(roots) != 2 {
		t.Errorf("Roots = %d, want 2", len(roots))
	}

	desc, err := svc.Descendants(top.ID)
	if err != nil {
		t.Fatalf("Descendants: %v", err)
	}
	if len(desc) != 2 {
		t.Errorf("Descendants = %d, want 2", len(desc))
	}

	// What a filter wants: this node AND everything under it.
	ids, err := svc.DescendantIDs(top.ID)
	if err != nil {
		t.Fatalf("DescendantIDs: %v", err)
	}
	if len(ids) != 3 {
		t.Errorf("DescendantIDs = %d, want 3 (self + 2)", len(ids))
	}

	crumbs, err := svc.Breadcrumbs(bottom.ID)
	if err != nil {
		t.Fatalf("Breadcrumbs: %v", err)
	}
	if len(crumbs) != 3 || crumbs[0].Name != "Top" || crumbs[2].Name != "Bottom" {
		t.Errorf("Breadcrumbs came back wrong: %+v", crumbs)
	}

	tree, err := svc.Tree()
	if err != nil {
		t.Fatalf("Tree: %v", err)
	}
	if len(tree) != 2 {
		t.Fatalf("Tree roots = %d, want 2", len(tree))
	}
	for _, node := range tree {
		if node.Name != "Top" {
			continue
		}
		if len(node.Children) != 1 || len(node.Children[0].Children) != 1 {
			t.Error("the tree is not nested three deep")
		}
	}
}

// The point of a materialized path: a move rewrites the subtree with it.
func TestCategoryTreeMoveCarriesTheSubtree(t *testing.T) {
	db := CategoryTreeTestDB(t)
	svc := services.NewCategoryTreeService(db)

	top := makeCategory(t, db, "Top", "")
	middle := makeCategory(t, db, "Middle", top.ID)
	bottom := makeCategory(t, db, "Bottom", middle.ID)
	other := makeCategory(t, db, "Other", "")

	if err := svc.Move(middle.ID, other.ID, 0); err != nil {
		t.Fatalf("Move: %v", err)
	}

	var movedMiddle, movedBottom models.Category
	db.Where("id = ?", middle.ID).First(&movedMiddle)
	db.Where("id = ?", bottom.ID).First(&movedBottom)

	wantMiddle := "/" + other.ID + "/" + middle.ID + "/"
	if movedMiddle.Path != wantMiddle || movedMiddle.Depth != 1 ||
		movedMiddle.ParentID == nil || *movedMiddle.ParentID != other.ID {
		t.Errorf("moved node: path=%q depth=%d root=%v", movedMiddle.Path, movedMiddle.Depth, movedMiddle.IsRoot())
	}
	if want := wantMiddle + bottom.ID + "/"; movedBottom.Path != want || movedBottom.Depth != 2 {
		t.Errorf("descendant: path=%q depth=%d, want %q depth 2", movedBottom.Path, movedBottom.Depth, want)
	}

	if ids, _ := svc.DescendantIDs(other.ID); len(ids) != 3 {
		t.Errorf("the new parent should hold 3 ids, holds %d", len(ids))
	}
	if ids, _ := svc.DescendantIDs(top.ID); len(ids) != 1 {
		t.Errorf("the old parent should be alone, holds %d", len(ids))
	}
}

func TestCategoryTreeMoveToRoot(t *testing.T) {
	db := CategoryTreeTestDB(t)
	svc := services.NewCategoryTreeService(db)

	top := makeCategory(t, db, "Top", "")
	child := makeCategory(t, db, "Child", top.ID)

	if err := svc.Move(child.ID, "", 0); err != nil {
		t.Fatalf("Move to root: %v", err)
	}
	var moved models.Category
	db.Where("id = ?", child.ID).First(&moved)
	if moved.Path != "/"+child.ID+"/" || moved.Depth != 0 || !moved.IsRoot() {
		t.Errorf("promoted node: path=%q depth=%d root=%v", moved.Path, moved.Depth, moved.IsRoot())
	}
}

// The invariant that matters most: without it the subtree is detached from the
// tree and no query ever finds it again.
func TestCategoryTreeRefusesACycle(t *testing.T) {
	db := CategoryTreeTestDB(t)
	svc := services.NewCategoryTreeService(db)

	top := makeCategory(t, db, "Top", "")
	middle := makeCategory(t, db, "Middle", top.ID)
	bottom := makeCategory(t, db, "Bottom", middle.ID)

	if err := svc.Move(top.ID, bottom.ID, 0); err == nil {
		t.Error("moving a node under its own descendant must be refused")
	}
	if err := svc.Move(top.ID, top.ID, 0); err == nil {
		t.Error("a node cannot be its own parent")
	}

	var check models.Category
	db.Where("id = ?", top.ID).First(&check)
	if !check.IsRoot() || check.Depth != 0 {
		t.Errorf("a refused move must leave the row untouched: root=%v depth=%d", check.IsRoot(), check.Depth)
	}
}

// Rows that predate --tree arrive with a NULL parent_id, because AutoMigrate
// fills a new column with NULL. Every query that means "is a root" has to say so
// in a way that matches those rows: "parent_id = ”" alone silently matches none
// of them, and a reorder that updates nothing still answers 200.
func TestCategoryTreeToleratesNullParents(t *testing.T) {
	db := CategoryTreeTestDB(t)
	svc := services.NewCategoryTreeService(db)

	a := makeCategory(t, db, "A", "")
	b := makeCategory(t, db, "B", "")
	// Exactly what adding --tree to an existing table leaves behind.
	db.Exec("UPDATE categories SET parent_id = NULL")

	roots, err := svc.Roots()
	if err != nil {
		t.Fatalf("Roots: %v", err)
	}
	if len(roots) != 2 {
		t.Errorf("Roots with NULL parents = %d, want 2", len(roots))
	}

	if err := svc.Reorder("", []string{b.ID, a.ID}); err != nil {
		t.Fatalf("Reorder: %v", err)
	}
	ordered, _ := svc.Roots()
	if len(ordered) != 2 || ordered[0].Name != "B" {
		names := []string{}
		for _, r := range ordered {
			names = append(names, r.Name)
		}
		t.Errorf("order = %v, want [B A]", names)
	}
}

// Moving a node that has no path must not touch any other row.
//
// The bug this pins down: "" as a LIKE prefix matches every row in the table, so
// the subtree rewrite that follows a move landed on all of them and added one to
// every depth in the database. A node with no path is one that predates --tree,
// which makes this the normal case the first time somebody drags a row after
// adding the flag to an existing table.
func TestCategoryTreeMoveOfAPathlessNodeLeavesOthersAlone(t *testing.T) {
	db := CategoryTreeTestDB(t)
	svc := services.NewCategoryTreeService(db)

	top := makeCategory(t, db, "Top", "")
	middle := makeCategory(t, db, "Middle", top.ID)
	bottom := makeCategory(t, db, "Bottom", middle.ID)

	// A row as AutoMigrate leaves it when --tree is added to an existing table.
	stray := makeCategory(t, db, "Stray", "")
	db.Model(&models.Category{}).Where("id = ?", stray.ID).
		Updates(map[string]any{"path": "", "depth": 0, "parent_id": nil})

	if err := svc.Move(stray.ID, top.ID, 0); err != nil {
		t.Fatalf("Move: %v", err)
	}

	var movedStray, checkTop, checkMiddle, checkBottom models.Category
	db.Where("id = ?", stray.ID).First(&movedStray)
	db.Where("id = ?", top.ID).First(&checkTop)
	db.Where("id = ?", middle.ID).First(&checkMiddle)
	db.Where("id = ?", bottom.ID).First(&checkBottom)

	// The moved row is repaired.
	if movedStray.Depth != 1 || movedStray.Path != top.Path+stray.ID+"/" {
		t.Errorf("moved node: path=%q depth=%d", movedStray.Path, movedStray.Depth)
	}
	// And nothing else moved an inch.
	if checkTop.Depth != 0 || checkMiddle.Depth != 1 || checkBottom.Depth != 2 {
		t.Errorf("depths of untouched rows changed: %d %d %d, want 0 1 2",
			checkTop.Depth, checkMiddle.Depth, checkBottom.Depth)
	}
	if checkBottom.Path != checkMiddle.Path+bottom.ID+"/" {
		t.Errorf("an untouched path was rewritten: %q", checkBottom.Path)
	}
}

func TestCategoryTreeReorderAndRebuild(t *testing.T) {
	db := CategoryTreeTestDB(t)
	svc := services.NewCategoryTreeService(db)

	root := makeCategory(t, db, "Root", "")
	a := makeCategory(t, db, "A", root.ID)
	b := makeCategory(t, db, "B", root.ID)
	c := makeCategory(t, db, "C", root.ID)

	if err := svc.Reorder(root.ID, []string{c.ID, a.ID, b.ID}); err != nil {
		t.Fatalf("Reorder: %v", err)
	}
	children, _ := svc.Children(root.ID)
	if got := fmt.Sprintf("%s,%s,%s", children[0].Name, children[1].Name, children[2].Name); got != "C,A,B" {
		t.Errorf("order = %s, want C,A,B", got)
	}

	// A bulk import that went around the hooks leaves paths empty, and Rebuild
	// has to reconstruct them from parent_id alone.
	db.Exec("UPDATE categories SET path = '', depth = 0")
	if err := svc.RebuildPaths(); err != nil {
		t.Fatalf("RebuildPaths: %v", err)
	}
	var rebuilt models.Category
	db.Where("id = ?", a.ID).First(&rebuilt)
	if want := "/" + root.ID + "/" + a.ID + "/"; rebuilt.Path != want || rebuilt.Depth != 1 {
		t.Errorf("rebuilt: path=%q depth=%d, want %q depth 1", rebuilt.Path, rebuilt.Depth, want)
	}
	_ = b
}
