package handlers

import (
	"net/http"
	"strconv"

	"github.com/gin-gonic/gin"

	"storefront/apps/api/internal/files"
	"storefront/apps/api/internal/models"
	"storefront/apps/api/internal/paginate"
)

// The public categories surface.
//
// Generated by grit with --public. Two read endpoints, mounted outside auth and
// guarded by an API key, for clients with no logged-in user: a storefront, a
// mobile app, a public directory.
//
// Regenerating the resource does NOT overwrite this file, so the allowlist
// below is yours to edit.

// publicCategory is what an anonymous caller is allowed to see.
//
// An allowlist rather than the model. A column added next month is private
// until somebody adds it here, which is the correct default when the audience
// is the internet, and the opposite of the admin surface's default.
type publicCategory struct {
	ID            string         `json:"id"`
	ParentID      string         `json:"parent_id"`
	Depth         int            `json:"depth"`
	DescendantIDs []string       `json:"descendant_ids,omitempty"`
	Name          string         `json:"name"`
	Slug          string         `json:"slug"`
	Description   string         `json:"description"`
	Image         *files.FileRef `json:"image"`
	Featured      bool           `json:"featured"`
}

func toPublicCategory(m models.Category) publicCategory {
	return publicCategory{
		ID:          m.ID,
		ParentID:    derefCategoryID(m.ParentID),
		Depth:       m.Depth,
		Name:        m.Name,
		Slug:        m.Slug,
		Description: m.Description,
		Image:       m.Image,
		Featured:    m.Featured,
	}
}

// ListPublic handles GET /api/v1/public/categories.
//
// Supports ?search=, ?sort_by= and ?sort_order=, ?page= and ?page_size=,
// equality filters on the published columns, and a ?x_min= / ?x_max= window on
// the numeric ones.
func (h *CategoryHandler) ListPublic(c *gin.Context) {
	// Scoped before paginate sees it, and archived_at is deliberately absent
	// from the filter lists below: a column listed there is settable from the
	// query string, so ?archived=true would hand back rows somebody took down
	// on purpose.
	query := h.DB.Model(&models.Category{}).Where("archived_at IS NULL")

	res, err := paginate.List[models.Category](
		query,
		paginate.Bind(c),
		paginate.Config{
			Searchable: []string{"name", "slug", "description"},
			Sortable:   map[string]bool{"name": true, "slug": true, "description": true, "created_at": true},
			// Published columns only, plus foreign keys. Anything not listed
			// is ignored rather than rejected, so an unknown query param is
			// never an error.
			Filterable:      map[string]bool{"name": true, "slug": true, "featured": true},
			RangeFilterable: map[string]bool{},
			// Foreign keys accept a comma-separated list, so one request can
			// ask for a whole category subtree.
			InFilterable: map[string]bool{"parent_id": true},
		},
	)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": gin.H{
			"code": "INTERNAL_ERROR", "message": "Failed to fetch categories",
		}})
		return
	}

	out := make([]publicCategory, 0, len(res.Data))
	for _, m := range res.Data {
		out = append(out, toPublicCategory(m))
	}
	c.JSON(http.StatusOK, gin.H{"data": out, "meta": res.Meta})
}

// GetPublic handles GET /api/v1/public/categories/:key.
//
// Looks up by slug, so a public URL reads as something a person
// could type rather than a UUID.
func (h *CategoryHandler) GetPublic(c *gin.Context) {
	var item models.Category
	err := h.DB.Where("slug = ? AND archived_at IS NULL", c.Param("key")).
		First(&item).Error
	if err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": gin.H{
			"code": "NOT_FOUND", "message": "Category not found",
		}})
		return
	}

	// This node and everything under it, which is what "products in Electronics"
	// means to a customer. One indexed LIKE on the materialized path.
	out := toPublicCategory(item)
	var descendantIDs []string
	h.DB.Model(&models.Category{}).
		Where("path LIKE ? AND archived_at IS NULL", item.Path+"%").
		Pluck("id", &descendantIDs)
	out.DescendantIDs = descendantIDs
	c.JSON(http.StatusOK, gin.H{"data": out})
}

// derefID renders a nullable foreign key for the wire.
//
// The parent column is a *string because a root has no parent and SQL spells
// absent as NULL, which a foreign key constraint accepts and an empty string
// does not. JSON has the same choice to make, and "" reads better to a client
// than null for an id it is only going to compare.
func derefCategoryID(id *string) string {
	if id == nil {
		return ""
	}
	return *id
}

// publicParentOf resolves a row's parent in the node map, treating NULL and ""
// alike as no parent. Both turn up in real data: NULL from a root written now,
// "" from a row written before the column was nullable.
func publicCategoryParentOf(byID map[string]*publicCategoryNode, parentID *string) (*publicCategoryNode, bool) {
	if parentID == nil || *parentID == "" {
		return nil, false
	}
	node, ok := byID[*parentID]
	return node, ok
}

// publicCategoryNode is a published node with its children attached.
//
// The embedded struct flattens in JSON, so a node reads as its own fields plus
// "children" rather than nesting one level deeper for no reason.
type publicCategoryNode struct {
	publicCategory
	Children []*publicCategoryNode `json:"children"`
}

// TreePublic handles GET /api/v1/public/categories/tree.
//
// The whole published hierarchy in ONE query, assembled in Go. Ordered by depth
// so a parent is always in the map before its children arrive, then by position
// and name so the order matches what the admin arranged.
func (h *CategoryHandler) TreePublic(c *gin.Context) {
	var rows []models.Category
	err := h.DB.Where("archived_at IS NULL").
		Order("depth asc, position asc, name asc").
		Find(&rows).Error
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": gin.H{
			"code": "INTERNAL_ERROR", "message": "Failed to load the tree",
		}})
		return
	}

	byID := make(map[string]*publicCategoryNode, len(rows))
	roots := make([]*publicCategoryNode, 0)
	for i := range rows {
		byID[rows[i].ID] = &publicCategoryNode{publicCategory: toPublicCategory(rows[i])}
	}
	for i := range rows {
		node := byID[rows[i].ID]
		// A node whose parent is archived is promoted to a root rather than
		// dropped: a menu missing a whole branch is worse than one with a branch
		// in the wrong place.
		if parent, ok := publicCategoryParentOf(byID, rows[i].ParentID); ok {
			parent.Children = append(parent.Children, node)
			continue
		}
		roots = append(roots, node)
	}
	c.JSON(http.StatusOK, gin.H{"data": roots})
}

// RelatedPublic handles GET /api/v1/public/categories/:key/related.
//
// The "similar items" strip on a detail page: others sharing this one's
// parent, newest first, this one excluded.
//
// Capped at 24 however large ?limit= asks, because this endpoint exists to
// fill a row of cards and an uncapped limit on a public route is a free way
// to make the database do work.
func (h *CategoryHandler) RelatedPublic(c *gin.Context) {
	var item models.Category
	err := h.DB.Where("slug = ? AND archived_at IS NULL", c.Param("key")).
		First(&item).Error
	if err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": gin.H{
			"code": "NOT_FOUND", "message": "Category not found",
		}})
		return
	}

	limit := 8
	if raw := c.Query("limit"); raw != "" {
		if n, convErr := strconv.Atoi(raw); convErr == nil && n > 0 {
			limit = n
		}
	}
	if limit > 24 {
		limit = 24
	}

	query := h.DB.Model(&models.Category{}).
		Where("id <> ? AND archived_at IS NULL", item.ID)
	// A row with no parent has no siblings, and an empty strip on
	// a detail page looks broken. Falling back to the newest rows is a worse
	// recommendation than a real match and a better one than nothing.
	if item.ParentID != nil && *item.ParentID != "" {
		query = query.Where("parent_id = ?", *item.ParentID)
	}

	var rows []models.Category
	if err := query.Order("created_at desc").Limit(limit).Find(&rows).Error; err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": gin.H{
			"code": "INTERNAL_ERROR", "message": "Failed to fetch related categories",
		}})
		return
	}

	out := make([]publicCategory, 0, len(rows))
	for _, m := range rows {
		out = append(out, toPublicCategory(m))
	}
	c.JSON(http.StatusOK, gin.H{"data": out})
}
