package handlers

import (
	"net/http"
	"strconv"

	"github.com/gin-gonic/gin"

	"storefront/apps/api/internal/files"
	"storefront/apps/api/internal/models"
	"storefront/apps/api/internal/paginate"
)

// The public products surface.
//
// Generated by grit with --public. Two read endpoints, mounted outside auth and
// guarded by an API key, for clients with no logged-in user: a storefront, a
// mobile app, a public directory.
//
// Regenerating the resource does NOT overwrite this file, so the allowlist
// below is yours to edit.

// publicProduct is what an anonymous caller is allowed to see.
//
// An allowlist rather than the model. A column added next month is private
// until somebody adds it here, which is the correct default when the audience
// is the internet, and the opposite of the admin surface's default.
type publicProduct struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Slug           string         `json:"slug"`
	Sku            string         `json:"sku"`
	Description    string         `json:"description"`
	Price          float64        `json:"price"`
	CompareAtPrice float64        `json:"compare_at_price"`
	Images         files.FileRefs `json:"images"`
}

func toPublicProduct(m models.Product) publicProduct {
	return publicProduct{
		ID:             m.ID,
		Name:           m.Name,
		Slug:           m.Slug,
		Sku:            m.Sku,
		Description:    m.Description,
		Price:          m.Price,
		CompareAtPrice: m.CompareAtPrice,
		Images:         m.Images,
	}
}

// ListPublic handles GET /api/v1/public/products.
//
// Supports ?search=, ?sort_by= and ?sort_order=, ?page= and ?page_size=,
// equality filters on the published columns, and a ?x_min= / ?x_max= window on
// the numeric ones.
func (h *ProductHandler) ListPublic(c *gin.Context) {
	// Scoped before paginate sees it, and archived_at is deliberately absent
	// from the filter lists below: a column listed there is settable from the
	// query string, so ?archived=true would hand back rows somebody took down
	// on purpose.
	query := h.DB.Model(&models.Product{}).Where("archived_at IS NULL")

	res, err := paginate.List[models.Product](
		query,
		paginate.Bind(c),
		paginate.Config{
			Searchable: []string{"name", "slug", "sku"},
			Sortable:   map[string]bool{"name": true, "slug": true, "sku": true, "price": true, "compare_at_price": true, "created_at": true},
			// Published columns only, plus foreign keys. Anything not listed
			// is ignored rather than rejected, so an unknown query param is
			// never an error.
			Filterable:      map[string]bool{"name": true, "slug": true, "sku": true, "price": true, "compare_at_price": true},
			RangeFilterable: map[string]bool{"price": true, "compare_at_price": true},
			// Foreign keys accept a comma-separated list, so one request can
			// ask for a whole category subtree.
			InFilterable: map[string]bool{"category_id": true},
		},
	)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": gin.H{
			"code": "INTERNAL_ERROR", "message": "Failed to fetch products",
		}})
		return
	}

	out := make([]publicProduct, 0, len(res.Data))
	for _, m := range res.Data {
		out = append(out, toPublicProduct(m))
	}
	c.JSON(http.StatusOK, gin.H{"data": out, "meta": res.Meta})
}

// GetPublic handles GET /api/v1/public/products/:key.
//
// Looks up by slug, so a public URL reads as something a person
// could type rather than a UUID.
func (h *ProductHandler) GetPublic(c *gin.Context) {
	var item models.Product
	err := h.DB.Where("slug = ? AND archived_at IS NULL", c.Param("key")).
		First(&item).Error
	if err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": gin.H{
			"code": "NOT_FOUND", "message": "Product not found",
		}})
		return
	}
	c.JSON(http.StatusOK, gin.H{"data": toPublicProduct(item)})
}

// RelatedPublic handles GET /api/v1/public/products/:key/related.
//
// The "similar items" strip on a detail page: others sharing this one's
// category, newest first, this one excluded.
//
// Capped at 24 however large ?limit= asks, because this endpoint exists to
// fill a row of cards and an uncapped limit on a public route is a free way
// to make the database do work.
func (h *ProductHandler) RelatedPublic(c *gin.Context) {
	var item models.Product
	err := h.DB.Where("slug = ? AND archived_at IS NULL", c.Param("key")).
		First(&item).Error
	if err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": gin.H{
			"code": "NOT_FOUND", "message": "Product not found",
		}})
		return
	}

	limit := 8
	if raw := c.Query("limit"); raw != "" {
		if n, convErr := strconv.Atoi(raw); convErr == nil && n > 0 {
			limit = n
		}
	}
	if limit > 24 {
		limit = 24
	}

	query := h.DB.Model(&models.Product{}).
		Where("id <> ? AND archived_at IS NULL", item.ID)
	// A row with no category has no siblings, and an empty strip on
	// a detail page looks broken. Falling back to the newest rows is a worse
	// recommendation than a real match and a better one than nothing.
	if item.CategoryID != "" {
		query = query.Where("category_id = ?", item.CategoryID)
	}

	var rows []models.Product
	if err := query.Order("created_at desc").Limit(limit).Find(&rows).Error; err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": gin.H{
			"code": "INTERNAL_ERROR", "message": "Failed to fetch related products",
		}})
		return
	}

	out := make([]publicProduct, 0, len(rows))
	for _, m := range rows {
		out = append(out, toPublicProduct(m))
	}
	c.JSON(http.StatusOK, gin.H{"data": out})
}
